services:
  eventschedulingsystem:
    build:
      context: .
      dockerfile: EventSchedulingSystem/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5434;Database=EventSchedulingDb;Username=postgres;Password=123
    ports:
      - "8081:80"
      - "8082:443"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: EventSchedulingDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
